from django.urls import path
from .views import (MetalDetailsView, MetalListView, PurityDetailsView, PurityListView, SchemeClassListView,
                    SchemeClassDetailsView, ClarityListView, ClarityDetailsView,ColorListView,ColorDetailsView,
                    ShapeListView,ShapeDetailsView, CutListView, CutDetailsView, CategoryDetailsView, CategoryListView,
                    OutStockProductListView,ActiveProductListView,ProductDetailsView, QualityCodeView, QualityDetailsView, StoneListView,ProductListView,DesignListView,SubDesignListView,DesignMappingView,SubDesignMappingView,
                    MakingAndWastageSettingsListView, StoneDetailsView,MakingAndWastageSettingsListView,MakingAndWastageSettingsCreateView,InStockProductListView,
                    SectionListView,SectionDetailsView,ProductCalculationTypeListView,SubDesignDetailsView,DesignDetailsView,
                    DiamondRatemasterCreateView, DiamondRatemasterDetailsView, ErpReorderSettingsListCreateView,RepairDamageMasterListView,RepairDamageMasterView,
                    CounterWiseTargetListView, CounterWiseTargetItemsListView,CustomerMakingAndWastageSettingsListView, CustomerMakingAndWastageSettingsCreateView,CustomerEnquiryListView,
                    DiamondRateFilterView, PurchaseDiamondRateFilterView, PurchaseDiamondRatemasterCreateView, CategoryPurityRateView, CategoryPurityRateListView,CategoryPurityRates,
                    NewArrivalsProductListView, CustomerEnquiryProducts, CustomerEnquiryDesignsAndWeightOfProducts)

urlpatterns = [
        path('diamond_rate/', DiamondRatemasterCreateView.as_view()),
        path('cat_metal_rates/', CategoryPurityRates.as_view()),
        path('purchase_diamond_rate/', PurchaseDiamondRatemasterCreateView.as_view()),
        path('diamond_rate_filter/', DiamondRateFilterView.as_view()),
        path('purchase_diamond_rate_filter/', PurchaseDiamondRateFilterView.as_view()),
        path('diamond_rate/<int:pk>/', DiamondRatemasterDetailsView.as_view()),
        path('reorder_setting/', ErpReorderSettingsListCreateView.as_view()),
        path('metal/', MetalListView.as_view()),
        path('metal/<int:pk>/', MetalDetailsView.as_view()),
        path('purity/', PurityListView.as_view()),
        path('purity/<int:pk>/', PurityDetailsView.as_view()),
        path('clarity/', ClarityListView.as_view()),
        path('clarity/<int:pk>/', ClarityDetailsView.as_view()),
        path('scheme_class/', SchemeClassListView.as_view()),
        path('scheme_class/<int:pk>/', SchemeClassDetailsView.as_view()),
        path('stone/', StoneListView.as_view()),
        path('stone/<int:pk>/', StoneDetailsView.as_view()),
        path('quality_code/', QualityCodeView.as_view()),
        path('quality/', QualityCodeView.as_view()),
        path('quality/<int:pk>/', QualityDetailsView.as_view()),
        path('color/', ColorListView.as_view()),
        path('color/<int:pk>/', ColorDetailsView.as_view()),
        path('shape/', ShapeListView.as_view()),
        path('shape/<int:pk>/', ShapeDetailsView.as_view()),
        path('cut/', CutListView.as_view()),
        path('cut/<int:pk>/', CutDetailsView.as_view()),
        path('category/', CategoryListView.as_view()),
        path('category/<int:pk>/', CategoryDetailsView.as_view()),
        path('product/', ProductListView.as_view()),
        path('active_product/', ActiveProductListView.as_view()),
        path('outstock_product/', OutStockProductListView.as_view()),
        path('product/<int:pk>/', ProductDetailsView.as_view()),
        path('design/', DesignListView.as_view()),
        path('design/<int:pk>/', DesignDetailsView.as_view()),
        path('sub_design/', SubDesignListView.as_view()),
        path('sub_design/<int:pk>/', SubDesignDetailsView.as_view()),
        path('design_mapping/', DesignMappingView.as_view()),
        path('design_mapping/<int:pk>/', DesignMappingView.as_view()),
        path('sub_design_mapping/<int:pk>/', SubDesignMappingView.as_view()),
        path('sub_design_mapping/', SubDesignMappingView.as_view()),
        path('mc_va_setting/', MakingAndWastageSettingsCreateView.as_view()),
        path('mc_va_setting_list/', MakingAndWastageSettingsListView.as_view()),
        path('customer_mc_va_setting/', CustomerMakingAndWastageSettingsCreateView.as_view()),
        path('customer_mc_va_setting_list/', CustomerMakingAndWastageSettingsListView.as_view()),
        path('section/', SectionListView.as_view()),
        path('section/<int:pk>/', SectionDetailsView.as_view()),
        path('caltype/', ProductCalculationTypeListView.as_view()),
        path('counter_wise_target_items/', CounterWiseTargetItemsListView.as_view()),
        path('counter_wise_target/', CounterWiseTargetListView.as_view()),
        path('repair_master/', RepairDamageMasterListView.as_view()),
        path('repair_master/<int:pk>/', RepairDamageMasterView.as_view()),
        path('category_purity_rate_list/', CategoryPurityRateListView.as_view()),
        path('category_purity_rate/', CategoryPurityRateView.as_view()),
        # path('counter_wise_target/<int:pk>/', CounterWiseTargetDetailView.as_view()),
        path('instock_product_list/', InStockProductListView.as_view()),
        path('new_arrivals/', NewArrivalsProductListView.as_view()),
        path('customer_enquiry/', CustomerEnquiryListView.as_view()),
        path('customer_enquiry_products/', CustomerEnquiryProducts.as_view()),
        path('customer_enquiry_designs_weights/', CustomerEnquiryDesignsAndWeightOfProducts.as_view()),
]