from django.urls import path

from .views import (LotInwardListView,LotDetailsView ,TagListView, ErpLotCreateAPIView,ErpTagCreateAPIView,
                    ErpNonTagStockAPIView,ErpBulkEditAPIView,TagAutoCompete,ErpNonTagStockStoneAPIView,TagIssueListView,LotIssueListView,
                    ErpTagScanCloseView,ErpTagScanView,PartlySoldTagListView, ErpTaggingContainerLogDetailsCreateView,
                    ErpTaggingContainerLogDetailsListView,ErpTagContainerScanDetailView,ErpTagContainerScanCloseView,LotQRPrintView,
                    BulkTagPrintView,LotIssueDetailListView,TagIssueDetailListView,ErpNonTagLotInwardAPIView,LotNonTagListView,
                    TagSearchAPIView, AdminAppTagImageEdit, AdminAppTagSearch,NonTagInwardListView, AdminAppTagImageDelete,LotIssueReceiptPrintView,
                    LotProductClose,ErpTagPrintAPIView, ErpTagSetListCreateView,LotBalanceDetailView,LotMergeDetail,TagSqlListView,ErpTagSetDetailView,ErpRemoveTagSetDetailView,TagImagePrintPDFView)


urlpatterns = [
    path('lot/list/', LotInwardListView.as_view()),
    path('lot/create/', ErpLotCreateAPIView.as_view()),
    path('lot/print/<int:pk>/', ErpLotCreateAPIView.as_view()),
    path('lot/qr_print/', LotQRPrintView.as_view()),
    path('lot/update/<int:pk>/', LotDetailsView.as_view()),
    path('lot/lot_balance/<int:lot_inward_detail_id>/', LotInwardListView.as_view()),
    path('lot/<int:pk>/', LotDetailsView.as_view()),
    path('lot/lot_details/', LotDetailsView.as_view()),
    path('tag/list/', TagSqlListView.as_view()),
    path('tag/create/', ErpTagCreateAPIView.as_view()),
    path('tag/update/', ErpTagCreateAPIView.as_view()),
    path('tag/print/', ErpTagPrintAPIView.as_view()),
    path('tag/assign_container/', ErpTaggingContainerLogDetailsCreateView.as_view()),
    path('tag/container/list/', ErpTaggingContainerLogDetailsListView.as_view()),
    path('tag/delete/<int:pk>/', TagListView.as_view()),
    path('lot/lot_product_close/<int:pk>/', LotProductClose.as_view()),
    path('bulk_tag_edit/update/', ErpBulkEditAPIView.as_view()),
    path('bulk_tag/print/', BulkTagPrintView.as_view()),
    path('bulk_tag_edit/tag_data/', ErpBulkEditAPIView.as_view()),
    path('nontag/stock/', ErpNonTagStockAPIView.as_view()),
    path('nontag_stone/stock/', ErpNonTagStockStoneAPIView.as_view()),
    path('tag/autoCompete/', TagAutoCompete.as_view()),
    path('tag/filterdList/', TagAutoCompete.as_view()),
    path('tag_audit/tag_scan/', ErpTagScanView.as_view()),
    path('tag_audit/close_scan/', ErpTagScanCloseView.as_view()),
    path('tag/partly_sold/', PartlySoldTagListView.as_view()),
    path('tag_audit/container_scan/', ErpTagContainerScanDetailView.as_view()),
    path('tag_audit/close_container_scan/', ErpTagContainerScanCloseView.as_view()),
    path('lot_product_details/', LotIssueDetailListView.as_view()),
    path('lot/issue_receipt/create/', LotIssueDetailListView.as_view()),   
    path('tag_product_details/', TagIssueDetailListView.as_view()),
    path('tag/issue_receipt/create/', TagIssueDetailListView.as_view()),   
    path('tag/issue_receipt/list/', TagIssueListView.as_view()),   
    path('lot/issue_receipt/list/', LotIssueListView.as_view()),  
    path('lot/issue_receipt/print/<int:pk>/', LotIssueReceiptPrintView.as_view()),  
    path('nontag_lot/', ErpNonTagLotInwardAPIView.as_view()),
    path('non_tag_lot/list/', LotNonTagListView.as_view()), 
    path('tag_search_deails/', TagSearchAPIView.as_view()), 
    path('lot/non_tag_lot_inward/create/', LotNonTagListView.as_view()), 
    path('lot/non_tag_lot_inward/list/', NonTagInwardListView.as_view()), 
    path('tag/admin_app/image_update/', AdminAppTagImageEdit.as_view()), 
    path('tag/admin_app/image_delete/', AdminAppTagImageDelete.as_view()), 
    path('tag/admin_app/search/', AdminAppTagSearch.as_view()), 
    path('tag/tag_set/list/', ErpTagSetListCreateView.as_view()), 
    path('lot/lot_balance_list/', LotBalanceDetailView.as_view()), 
    path('lot/lot_merge/add/', LotMergeDetail.as_view()), 
    path('tag/tag_set/<int:pk>/', ErpTagSetDetailView.as_view()), 
    path('tag/remove_tag_set/', ErpRemoveTagSetDetailView.as_view()), 
    path('tag/image/print/', TagImagePrintPDFView.as_view()), 
    
]