from django.urls import path

from .views import (BranchList, BranchAPI, CompanyAPI, CountryListView, CountryDetailsView, StateViewAPI, CityViewAPI,IncentiveSettingsDetailsView,
                    DepartmentDetailView, DepartmentListView, DesignationListView,
                    DesignationDetailView, BankListView, BankDetailView, PaymentModeListView,
                    PaymentModeDetailView, AreaListView, AreaDetailView, ProfessionListView,
                    ProfessionDetailView, TenantListView, TenantDetailView, MetalRatesListView,
                    MetalRatesDetailView, DistrictViewAPI, RetUomListView,
                    RetUomDetailView, CurrencyListView, TaxmasterListView, TaxmasterDetailView,
                    FinancialYearDetails, TaxgroupmasterAPI, TaxgroupmasteDetails, CurrencyDetails,
                    ProfileListView, ProfileDetailView, ExchangeRatesView, ExchangeRatesDetailView,
                    PayDeviceListView, PayDeviceDetailView, PaymentGatewayListView, PaymentGatewayDetailView, DistrictViewDetailAPI,
                    StateViewDetailAPI, CityDetailViewAPI, BannerList, RestDayCloseView,
                    BannerDetails, NBTypeListView, NBTypeDetailView, WeightRangeDetailsView, WeightRangeListView, SizeDetailsView, SizeListView,
                    MetalRatePurityListView, SupplierListView, AttributeEntryListView, AttributeEntryDetailView,
                    OtherChargesDetailView, OtherChargesListView, ErpOrderStatusListView, ManualDayCloseView, AutomaticDayCloseView, StockIssueTypeDetailView,
                    StockIssueTypeListView, DayCloseVerificationView, DayCloseVerifyUpdateView, BranchStatusUpdateView,
                    SupplierDetailView, DailyUpdateMetalRatesView, FloorDetailView, FloorListView, CounterDetailView, CounterListView,
                    RegisteredDevicesListView, RegisteredDevicesDetailView, RelationTypeListView, ContainerDetailView, ContainerListView,
                    OldMetalItemTypeListView,OldMetalItemTypeDetailView, ContainerPrintView,OtherWeightListView,OtherWeightDetailView,
                    CashOpeningBalanceDetailView,CashOpeningBalanceListView,AccountHeadListView,AccountHeadDetailView,BankDepositListView,BankDetailView,BankDepositDetailView,
                    ErpServiceListView, ErpServiceDetailsView, CustomerProofDetailsView, CustomerProofListView, SupplierProductView, RelationTypeDetailView,
                    DepositMasterListView,DepositMasterDetailsView, CustomerDepositListView,IncentiveSettingsListView,ReligionDetailView,ReligionListView,
                    CounterWiseTargetDetailsView, CustomerNotificationMasterListCreateView, BannerListCreateView, DailyStatusMasterListCreateView,
                    DailyStatusMasterDetailView, CompanyInfoApi,RegionListView,RegionDetailView)
from reports.views import (FinancialYearListView)

urlpatterns = [
    path('erporder_status/', ErpOrderStatusListView.as_view()),
    path('day_close_verify/', DayCloseVerificationView.as_view()),
    path('day_close_update/', DayCloseVerifyUpdateView.as_view()),
    path('day_close_manual/', ManualDayCloseView.as_view()),
    path('day_close_automatic/', AutomaticDayCloseView.as_view()),
    path('day_close_reset/', RestDayCloseView.as_view()),
    path('company/', CompanyAPI.as_view()),
    path('company_info/', CompanyInfoApi.as_view()),
    path('branch/', BranchAPI.as_view()),
    path('branch_status/<int:pk>/', BranchStatusUpdateView.as_view()),
    path('active_branch/', BranchList.as_view()),
    path('relation_type/', RelationTypeListView.as_view()),
    path('relation_type/<int:pk>/', RelationTypeDetailView.as_view()),
    path('country/', CountryListView.as_view()),
    path('country/<int:pk>/', CountryDetailsView.as_view()),
    path('district/', DistrictViewAPI.as_view()),
    path('district/<int:pk>/', DistrictViewDetailAPI.as_view()),
    path('state/', StateViewAPI.as_view()),
    path('state/<int:pk>/', StateViewDetailAPI.as_view()),
    path('city/', CityViewAPI.as_view()),
    path('city/<int:pk>/', CityDetailViewAPI.as_view()),
    path('department/', DepartmentListView.as_view()),
    path('department/<int:pk>/', DepartmentDetailView.as_view()),
    path('designation/', DesignationListView.as_view()),
    path('designation/<int:pk>/', DesignationDetailView.as_view()),
    path('bank/', BankListView.as_view()),
    path('bank/<int:pk>/', BankDetailView.as_view()),
    path('paymentmode/', PaymentModeListView.as_view()),
    path('paymentmode/<int:pk>/', PaymentModeDetailView.as_view()),
    path('area/', AreaListView.as_view()),
    path('area/<int:pk>/', AreaDetailView.as_view()),
    path('profession/', ProfessionListView.as_view()),
    path('profession/<int:pk>/', ProfessionDetailView.as_view()),
    path('tenant/', TenantListView.as_view()),
    path('tenant/<int:pk>/', TenantDetailView.as_view()),
    path('metal_rates/autoupdate/', DailyUpdateMetalRatesView.as_view()),
    path('metal_rates/', MetalRatesListView.as_view()),
    path('metal_rates/<int:pk>/', MetalRatesDetailView.as_view()),
    path('financial_year/', FinancialYearListView.as_view(), name='financial_year_list_create'),
    path('financial_year/<int:pk>/', FinancialYearDetails.as_view()),
    path('uom/', RetUomListView.as_view()),
    path('uom/<int:pk>/', RetUomDetailView.as_view()),
    path('currency/', CurrencyListView.as_view()),
    path('currency/<int:pk>/', CurrencyDetails.as_view()),
    path('taxmaster/', TaxmasterListView.as_view()),
    path('taxmaster/<int:pk>/', TaxmasterDetailView.as_view()),
    path('tax_group_master/', TaxgroupmasterAPI.as_view()),
    path('tax_group_master_edit/', TaxgroupmasteDetails.as_view()),
    path('profile/', ProfileListView.as_view()),
    path('profile/<int:pk>/', ProfileDetailView.as_view()),
    path('exchange_rate/', ExchangeRatesView.as_view()),
    path('exchange_rate/<int:pk>/', ExchangeRatesDetailView.as_view()),
    path('pay_device/', PayDeviceListView.as_view()),
    path('pay_device/<int:pk>/', PayDeviceDetailView.as_view()),
    path('nb_type/', NBTypeListView.as_view()),
    path('nb_type/<int:pk>/', NBTypeDetailView.as_view()),
    path('payment_gateway/', PaymentGatewayListView.as_view()),
    path('payment_gateway/<int:pk>/', PaymentGatewayDetailView.as_view()),
    path('banners/', BannerList.as_view(), name='listcreate_banners'),
    path('banner/', BannerListCreateView.as_view(),), #for admin
    path('banner/<int:pk>/', BannerDetails.as_view(),
         name='fetchupdatedelete_banner'),
    path('weight_range/', WeightRangeListView.as_view()),
    path('weight_range/<int:pk>/', WeightRangeDetailsView.as_view()),
    path('size/', SizeListView.as_view()),
    path('size/<int:pk>/', SizeDetailsView.as_view()),
    path('metal_purity_rate/', MetalRatePurityListView.as_view()),
    path('supplier/', SupplierListView.as_view()),
    path('supplier/<int:pk>/', SupplierDetailView.as_view()),
    path('attribute_entry/', AttributeEntryListView.as_view()),
    path('attribute_entry/<int:pk>/', AttributeEntryDetailView.as_view()),
    path('other_charges/', OtherChargesListView.as_view()),
    path('other_charges/<int:pk>/', OtherChargesDetailView.as_view()),
    path('stock_issue_type/', StockIssueTypeListView.as_view()),
    path('stock_issue_type/<int:pk>/', StockIssueTypeDetailView.as_view()),
    path('floor/', FloorListView.as_view()),
    path('floor/<int:pk>/', FloorDetailView.as_view()),
    path('counter/', CounterListView.as_view()),
    path('counter/<int:pk>/', CounterDetailView.as_view()),
    path('registered_device/', RegisteredDevicesListView.as_view()),
    path('registered_device/<int:pk>/', RegisteredDevicesDetailView.as_view()),
    path('container/', ContainerListView.as_view()),
    path('container/<int:pk>/', ContainerDetailView.as_view()),
    path('container_print/<int:pk>/', ContainerPrintView.as_view()),
    path('old_metal_item/', OldMetalItemTypeListView.as_view()),
    path('old_metal_item/<int:pk>/', OldMetalItemTypeDetailView.as_view()),
    path('other_weight/', OtherWeightListView.as_view()),
    path('other_weight/<int:pk>/', OtherWeightDetailView.as_view()),
    path('cash_opening_balance/', CashOpeningBalanceListView.as_view()),
    path('cash_opening_balance/<int:pk>/', CashOpeningBalanceDetailView.as_view()),
    path('account_head/', AccountHeadListView.as_view()),
    path('account_head/<int:pk>/', AccountHeadDetailView.as_view()),
    path('service/', ErpServiceListView.as_view()),
    path('service/<int:pk>/', ErpServiceDetailsView.as_view()),
    path('customer_proof/', CustomerProofListView.as_view()),
    path('customer_proof/<int:pk>/', CustomerProofDetailsView.as_view()),
    path('supplier_product/', SupplierProductView.as_view()),
    path('supplier_product/<int:pk>/', SupplierProductView.as_view()),
    path('bank_deposit/', BankDepositListView.as_view()),
    path('bank_deposit/<int:pk>/', BankDepositDetailView.as_view()),
    path('deposit_master/', DepositMasterListView.as_view()),
    path('deposit_master/<int:pk>/', DepositMasterDetailsView.as_view()),
    path('customer_deposit/', CustomerDepositListView.as_view()),
    path('incentive_settings/', IncentiveSettingsListView.as_view()),
    # path('incentive_settings/<int:pk>/', IncentiveSettingsDetailsView.as_view()),
    #path('customer_deposit/<int:pk>/', DepositMasterDetailsView.as_view()),
    path('religion_master/', ReligionListView.as_view()),
    path('religion_master/<int:pk>/', ReligionDetailView.as_view()),
    path('incentive_settings/<int:pk>/', CounterWiseTargetDetailsView.as_view()),
    path('customer_notification/', CustomerNotificationMasterListCreateView.as_view()),
    path('daily_status/', DailyStatusMasterListCreateView.as_view()),
    path('daily_status/<int:pk>/', DailyStatusMasterDetailView.as_view()),
    path('region/', RegionListView.as_view()),
    path('region/<int:pk>/', RegionDetailView.as_view()),
]
