from django.urls import path

from .views import *

urlpatterns = [
    path('collection_report/', CollectionReportView.as_view()),
    path('unpaid_report/', UnpaidReportView.as_view()),
    path('customer_outstanding_report/', CustomerOutstandingReportView.as_view()),
    path('month_wise_scheme_join/', MonthwiseSchemeJoinReportView.as_view()),
    path('month_wise_scheme_collection/', MonthwiseSchemeCollectionReportView.as_view()),
    path('chit_customer_report/', ChitCustomerReportView.as_view()),
    path('mode_wise_collection/', ModeWiseCollectionReportView.as_view()),
    path('closed_account_report/', ClosedAccountReportView.as_view()),
    path('scheme_wise_opening/', SchemeWiseOpeningAndClosingView.as_view()),
    #Retail Reports
    path('stock_in_and_out/', StockInAndOutAPIView.as_view()),
    path('available_stock/', TaggedStockSQLAPIView.as_view()),
    path('stock_transfer/', StockTransferAPIView.as_view()),
    path('sales_report/', SalesReportAPIView.as_view()),
    path('misc_bill_report/', MiscBillReportAPIView.as_view()),
    path('purchase_report/', PurchaseReportAPIView.as_view()),
    path('cash_abstract_report/', CashAbstractReportAPIView.as_view()),
    path('stock_audit_report/', StockAuditReportAPIView.as_view()),
    path('stock_audit_detail_report/', StockAuditDetailReportAPIView.as_view()),
    path('stock_audit_detail_report/print/', StockAuditDetailReportPrintAPIView.as_view()),

    path('b2b_sales_report/', B2BSalesReportAPIView.as_view()),
    path('advance_report/', AdvanceReportAPIView.as_view()),
    path('credit_report/', CreditReportAPIView.as_view()),
    path('credit_collection_report/', CreditCollectionReportAPIView.as_view()),
    path('reorder_report/', AIReorderReportView.as_view()),
    path('sales_prediction/', SalesPredictionReportView.as_view()),
    path('advance_adj/', AdvanceAdjReportAPIView.as_view()),
    path('chit_adj/', ChitAdjReportAPIView.as_view()),
    path('advance_refund/', AdvanceRefundReportAPIView.as_view()),
    path('sales_return_report/', SalesReturnReportAPIView.as_view()),
    path('emp_sales_report/', EmployeeSalesReportAPIView.as_view()),
    path('petty_cash_report/', PettyCashReportAPIView.as_view()),
    path('credit_pending_report/', CreditPendingReportAPIView.as_view()),
    path('credit_issue_pending_report/', CreditIssuedPendingReportAPIView.as_view()),
    path('partly_sales_report/', PartlySalesReportAPIView.as_view()),
    path('tag_wise_profit_report/', TagWiseProfitReportAPIView.as_view()),
    path('karigar_wise_sales_report/', KarigarWiseSalesReportAPIView.as_view()),
    path('discount_bill_report/', DiscountBillsReportAPIView.as_view()),
    path('billwise_transaction_report/', BillWiseTransactionReportAPIView.as_view()),
    path('cancel_bills_report/', CancelBillsReportAPIView.as_view()),
    path('sales_and_return_gst_report/', SalesAndReturnGstAbstractReportAPIView.as_view()),
    path('pan_bill_report/', PanBillsReportAPIView.as_view()),
    path('sales_target_report/', SalesTargetReportView.as_view()),
    path('credit_tobe_report/', CreditTobeReportAPIView.as_view()),
    path('jewel_not_delivered_report/', JewelNotDeliveredReportSqlAPIView.as_view()),
    path('metal_process_report/', MetalProcessReportAPIView.as_view()),
    path('category_wise_abstract_report/', CategoryWiseDailyAbstractReportAPIView.as_view()),
    path('other_metal_stock_in_and_out/', PurchaseStockInAndOutAPIView.as_view()),
    path('cash_book/',CashBookReportAPIView.as_view()),
    path('supplier_ledger/', SupplierLegerReportAPIView.as_view()),
    path('customer_ledger/', CustomerLedgerReportView.as_view()),
    path('other_metal_profit_loss_report/', OtherMetalProfitLossReportView.as_view()),
    path('get_cash_balance/', ClosingCash.as_view()),
    path('bank_statement_report/', BankStatementReportsAPIView.as_view()),
    path('re_order_report/', ReOrderReportAPIView.as_view()),
    path('above_2L_report/', Above2LReportAPIView.as_view()),
    path('incentive_report/', EmpIncentiveReportAPIView.as_view()),
    path('suppliers_ledger/', SupplierBalanceReportAPIView.as_view()),
    path('search_customer/', SearchCustomerHistory.as_view()),
    path('search_supplier/', SearchSupplierHistory.as_view()),
    path('search_tag/', SearchTagHistory.as_view()),
    path('sales_based_on_Weight_range_report/', SalesReportBasedOnWeightRangeAPIView.as_view()),
    path('payment_devices_wise_report/', PaymentDevicesReportsAPIView.as_view()),
    path('purchase_return_report/', PurchaseReturnReportView.as_view()),
    path('tag_details_report/', TagDetailsReportView.as_view()),
    path('supplier_catalog_report/', SupplierCatalogReportView.as_view()),
    
    path('stock_analysis/', StockAnalysisReportView.as_view()),
    path('lot_tag_product_details/', ProductLotandTagDetails.as_view()),
    path('cash_book_report/', CashBookReportAPI.as_view()),
    path('month_wise_sales/', MonthWiseSalesReportAPI.as_view()),
    path('month_wise_purchase_entry/', MonthWisePurchaseEntryReportAPI.as_view()),
    path('stock_inward_report/', StockInwardReportView.as_view()),
    path('lot_report/', LotReportView.as_view()),
    path('bill_view_report/', SalesItemReportAPIView.as_view()),
    path('digi_gold/', DigiGoldReportView.as_view()),
    path('account_wise_digi_gold/', DigiGoldAccountWiseReportView.as_view()),
    path('estimate_report/', EstimateReportAPIView.as_view()),
    path('lot_balance_report/', LotBalanceReportView.as_view()),
    path('stock_approval_pending/', StockApprovalPendingReportAPIView.as_view()),
    path('liablity_supplier_payment_report/', LiablitySupplierPaymentReportView.as_view()),
    path('stock_approval_report/', StockApprovalAPIView.as_view()),
    path('purchase_report_summary/', PurchaseReportSummary.as_view()),
    path('area_wise_sales_report/', AreaCustomerSalesLogReportAPIView.as_view()),
]