from django.urls import path

from .views import *

urlpatterns = [
    path('purchase_entry/list/', PurchaseEntryListView.as_view()),
    path('purchase_entry/create/', ErpPurchaseEntryCreateAPIView.as_view()),    
    path('purchase_entry/edit/<int:pk>/', PurchaseEntryEditView.as_view()),
    path('purchase_entry/edit/', PurchaseEntryEditView.as_view()),
    path('purchase_entry/update/<int:pk>/', PurchaseEntryEditView.as_view()), 
    path('purchase_entry/item_delete/', PurchaseEntryItemDeleteView.as_view()), 
    path('purchase_entry/cancel/', PurchaseEntryEditView.as_view()),    
    path('purchase_entry/print/<int:pk>/', ErpPurchaseEntryCreateAPIView.as_view()), 
    path('purchase_entry/get_po_details/', PurchaseEntryListView.as_view()), 
    path('purchase_entry/get_purchase_details/', PurchaseLotGenerateView.as_view()),
    path('lot_generate/', PurchaseLotGenerateView.as_view()),   
    path('issue_receipt/list/', PurchaseIssueReceiptListView.as_view()),  
    path('issue_receipt/create/', ErpPurchaseIssueReceiptCreateAPIView.as_view()),
    path('qu_issue_receipt/print/<int:pk>/', ErpPurchaseIssueReceiptCreateAPIView.as_view()),    
    path('issue_receipt/edit/<int:pk>/', ErpPurchaseIssueReceiptEditView.as_view()),   
    path('issue_receipt/cancel/', ErpPurchaseIssueReceiptEditView.as_view()),   
    path('purchase_payment/create/', ErpPurchasePaymentCreateAPIView.as_view()),
    path('customer_rate_cut/create/', ErpCustomerRateCutCreateAPIView.as_view()),
    path('purchase_payment/get_supplier_po_details/', ErpPurchasePaymentCreateAPIView.as_view()),
    path('purchase_stock_details/', GetPurchaseStockDetails.as_view()),   
    path('pending_transfer/create/', ErpAccountStockProcessCreateAPIView.as_view()),   
    path('metal_issue/create/', ErpMetalIssueCreateAPIView.as_view()),   
    path('metal_issue/list/', ErpMetalIssueListView.as_view()),  
    path('supplier_payment/create/', ErpSupplierPaymentCreateAPIView.as_view()),
    path('supplier_payment/print/<int:pk>/', ErpSupplierPaymentPrintAPIView.as_view()),
    path('supplier_payment/print_thermal/<int:pk>/', ErpSupplierPaymentPrintAPIView.as_view()),
    path('supplier_payment/list/', ErpSupplierPaymentPrintAPIView.as_view()),
    path('supplier_payment/get_supplier_po_details/', ErpSupplierPaymentCreateAPIView.as_view()),
    path('customer_payment/purchase_details/', ErpCustomerPaymentCreateAPIView.as_view()),
    path('customer_payment/create/', ErpCustomerPaymentCreateAPIView.as_view()),
    path('purchase_return/list/', ErpPurchaseReturnListView.as_view()),
    path('purchase_return/create/', ErpPurchaseReturnCreateView.as_view()),    
    path('purchase_return/<int:pk>/', ErpPurchaseReturnRetrieveUpdateView.as_view()),
    path('purchase_return/print/<int:pk>/', ErpPurchaseReturnPrintView.as_view()),
    path('purchase_return/cancel/', ErpPurchaseReturnCancelView.as_view()),
    path('purchase_payment/get_supplier_opening_details/', ErpSupplierOpeningDetailsAPIView.as_view()),
    path('purchase_payment/get_supplier_advance_details/', ErpSupplierAdvanceDetailsAPIView.as_view()),
    path('purchase_payment/get_supplier_cash_varavu/', ErpSupplierCashVaravuAPIView.as_view()),
    path('purchase_issue/print/<int:pk>/', ErpPurchaseIssueReceiptCreateAPIView.as_view()),
]