from django.urls import path
from .views import (ErpInvoiceCreateAPIView, ErpIssueReceiptListView, ErpIssueReceiptDetailView, ErpInvoiceDetailsAPIView,
                    ErpIssueReceiptCreateView, ErpIssueCreditsListView, ErpInvoiceListView, ErpInvoiceCancelView,
                    ErpInvoiceReturnDetailsView,ErpInvoiceCreditDetailsView, ErpIssueReceiptCancelView, ErpIssueReceiptPrintView,
                    ErpInvoiceAdvanceDetailsView,ErpInvoiceChitsDetailsView,InvoiceOnlinePaymentDetailsView,ErpInvoiceDiscountListView,
                    BankSettlementsListCreateView,BankSettlementListView,JewelNotDeliveredAPIView,ErpInvoiceDiscountCreateAPIView,
                    ErpInvoiceDepositDetailsView,ErpInvoiceDeleteDetailsAPIView,ErpInvoiceDeleteListAPIView,ErpInvoiceConvertsToNumberOneAPIView,
                    ErpIssueRecieptDeleteListAPIView, ErpIssueRecieptDeleteAPIView, JewelNotDeliveredProductWiseAPIView,ErpDeleteTransactionsAPIView,
                    ErpIssueReceiptPrintDetailsView, ErpLiablityEntryListCreateView, ErpLiablityEntryPayableListView,
                    JewelNotDeliveredRevertAPIView,ErpInvoiceSearchAPIView,ErpInvoiceSqlListView,
                    ErpLiablityPaymentListCreateView, ErpLiablityEntryPrintView, ErpLiablityPaymentPrintView,ErpCustomerSalesLogDetails)


urlpatterns = [
    path('create/', ErpInvoiceCreateAPIView.as_view()),
    path('search/', ErpInvoiceSearchAPIView.as_view()),
    #path('update/<int:pk>/', ErpInvoiceCreateAPIView.as_view()),
    path('edit/<int:pk>/', ErpInvoiceCreateAPIView.as_view()),
    path('print/<int:pk>/', ErpInvoiceCreateAPIView.as_view()),
    path('thermal_print/<int:pk>/', ErpInvoiceCreateAPIView.as_view()),
    path('bill_details/', ErpInvoiceDetailsAPIView.as_view()),
    path('update/<int:pk>/', ErpInvoiceDetailsAPIView.as_view()),
    path('issue_credits/list/', ErpIssueCreditsListView.as_view()),
    path('list/', ErpInvoiceSqlListView.as_view()),
    path('cancel/', ErpInvoiceCancelView.as_view()),
    path('issue_receipt/list/', ErpIssueReceiptListView.as_view()),
    path('issue_receipt/create/', ErpIssueReceiptCreateView.as_view()),
    path('issue_receipt/cancel/', ErpIssueReceiptCancelView.as_view()),
    path('issue_receipt/<int:pk>/', ErpIssueReceiptDetailView.as_view()),
    path('issue_receipt/print/<int:pk>/', ErpIssueReceiptPrintDetailsView.as_view()),
    path('return_details/', ErpInvoiceReturnDetailsView.as_view()),
    path('customer_credit/', ErpInvoiceCreditDetailsView.as_view()),
    path('customer_advance/', ErpInvoiceAdvanceDetailsView.as_view()),
    path('customer_deposit/', ErpInvoiceDepositDetailsView.as_view()),
    path('customer_chit/', ErpInvoiceChitsDetailsView.as_view()),
    path('online_payment_details/', InvoiceOnlinePaymentDetailsView.as_view()),
    path('bank_settlement_create/', BankSettlementsListCreateView.as_view()),
    path('bank_settlement/list', BankSettlementListView.as_view()),
    path('jewel_not_delivered/', JewelNotDeliveredAPIView.as_view()),
    path('jewel_not_delivered_cancel/', JewelNotDeliveredRevertAPIView.as_view()),
    path('discount_invoice_create/', ErpInvoiceDiscountCreateAPIView.as_view()),
    path('discount_invoice/list/', ErpInvoiceDiscountListView.as_view()),
    path('discount_print/<int:pk>/', ErpInvoiceDiscountCreateAPIView.as_view()),
    path('delete/', ErpInvoiceDeleteDetailsAPIView.as_view()),
    path('deleteable_bill_list/', ErpInvoiceDeleteListAPIView.as_view()),
    path('convert_bill_list/', ErpInvoiceConvertsToNumberOneAPIView.as_view()),
    path('deleteable_issuereciept_list/', ErpIssueRecieptDeleteListAPIView.as_view()),
    path('issuereciept_delete/', ErpIssueRecieptDeleteAPIView.as_view()),
    path('customer_jewel_not_delivered/', JewelNotDeliveredProductWiseAPIView.as_view()),
    path('delete_transaction/', ErpDeleteTransactionsAPIView.as_view()),
    path('liablity_entry/', ErpLiablityEntryListCreateView.as_view()),
    path('liablity_entry_payable/', ErpLiablityEntryPayableListView.as_view()),
    path('liablity_entry_payment/', ErpLiablityPaymentListCreateView.as_view()),
    path('liablity_entry/print/<int:pk>/', ErpLiablityEntryPrintView.as_view()),
    path('liablity_entry_payment/print/<int:pk>/', ErpLiablityPaymentPrintView.as_view()),
    path('customer_sales_log/', ErpCustomerSalesLogDetails.as_view()),
]